### ISSUE TITLE
Migration of PiNodeXMR repository Complete

### ISSUE THREAD

**Issue by shermand100** [shermand100/PiNodeXMR#108]
With reference to:

https://github.com/monero-ecosystem/meta/issues/78

It seems we need to find a new home. It's been great to be under the umbrella of the monero-ecosystem for all these years, and it was great for Eric and other members to agree to include us. It certainly helped with our project awareness around the Monero community but as he steps away from this repository I'm sure we'll be fine a new home.

This issue is created to 1) Allow your input to any restructuring we want to do whilst the move is going on. 2) Choose our new home 3) Add a checklist to bring all elements and links with us as part of the move.

To help direct any discussion:

1) I propose we re-clone this repo back to my personal account. It's where this came from and from here I can latter give permissions and needed to others. https://github.com/shermand100

2) Do we take this opportunity to remove the Sub-branches of this project? I'm tempted to.
Current structure has 'Master' branch to hold screenshots for the full user manual, readme, and most importantly the master version numbers called on by your updater scripts.
The sub-branches 'UbuntuServer-20.04' was to pull that version of PiNodeXMR depending on what OS you were running on. Legacy v4 PiNodeXMR also had RaspberryPi-OS, Debian Buster, Debian Bullseye etc.
I'd suggest that as we now solely operate on Ubuntu Server disk images, we can merge all into Master, which better aligns to how people expect a github repo to be laid out? Thoughts?

3) All Issues will remain open and Migrated

4) The to-be-archived monero-ecosystem PiNodeXMR will hold a "We've moved" style redirect to the new home.

5) This will of course require a mandatory update to ALL PiNodeXMR devices to correct to the new source file links on update. To confirm update of the system I propose we call after this fork PiNodeXMR v6. I may also be able to leave the support scripts (in setup menu) behind as a breadcrumb to allow devices that miss this update window to catch up after archiving?

Anything else I'm missing?
The news is a surprise to myself so I'm still processing if there are any other elements we need to bring with us.

Dan

**Comment by erciccione** [comment]
> The to-be-archived monero-ecosystem PiNodeXMR will hold a "We've moved" style redirect to the new home.

Note that when the project is transferred to the new home, there will be an automatic redirect from `monero-ecosystem/PiNode-XMR` to `NEW-PROJECT/PiNode-XMR`. You can fork the project and write a new link in the readme, but IMO the transation will be smoother and easier for you if the repo was simnply migrated (without forking it to a new place). Both ways will work anyway.

**Comment by shermand100** [comment]
Repository Transferred 12:00PM 22/01/2024

**Comment by shermand100** [comment]
> > It's been great to be under the umbrella of the monero-ecosystem for all these years
> 
> It was great to have you! :)
> 
> > The to-be-archived monero-ecosystem PiNodeXMR will hold a "We've moved" style redirect to the new home.
> 
> Note that when the project is transferred to the new home, there will be an automatic redirect from `monero-ecosystem/PiNode-XMR` to `NEW-PROJECT/PiNode-XMR`. You can fork the project and write a new link in the readme, but IMO the transation will be smoother and easier for you if the repo was simnply migrated (without forking it to a new place). Both ways will work anyway.

Yes, the repository transfer has gone better than I expected. Our users "Update PiNodeXMR" button seems to have auto-redirected to this repository so nobody should be left behind. A fairly seamless transition.
